### ISSUE TITLE
Can not run the project using xCode 14.3

### ISSUE THREAD

**Issue by vargajacint** [DakaiGroup/coinbase-waas-integration#3]
This is a known issue. Upgrading the react-native version solves this problem. Meanwhile, I've described a temporary solution in [another repository!](https://github.com/margelo/react-native-quick-crypto/issues/163#issuecomment-1504932726) Applying this patch to the React-Codgen pod will resolve this issue.

**Comment by gabkov** [comment]
i think this can be closed right? @vargajacint

**Comment by vargajacint** [comment]
Right✌🏼
